# Generated by Django 6.0 on 2025-12-12 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='ats.jobpost'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='matched_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='missing_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
    ]
