# Generated by Django 6.0 on 2025-12-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0002_candidate_job_candidate_matched_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='ai_grade',
            field=models.CharField(blank=True, help_text='AI match grade (A-F)', max_length=5),
        ),
        migrations.AddField(
            model_name='candidate',
            name='ai_reasoning',
            field=models.TextField(blank=True, help_text='AI analysis reasoning'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='ai_score',
            field=models.FloatField(blank=True, default=0, help_text='AI semantic match score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='fuzzy_matches',
            field=models.JSONField(blank=True, default=dict, help_text='Fuzzy matched keywords'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='keyword_score',
            field=models.FloatField(default=0, help_text='Enhanced keyword-based score (0-100)'),
        ),
    ]
